/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import Controller.LoginVM;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author elmer
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSMetroTextFullPlaceHolderBeanInfo1 = new rojerusan.RSMetroTextFullPlaceHolderBeanInfo();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rSLabelImage2 = new rojerusan.RSLabelImage();
        rSLabelImage1 = new rojerusan.RSLabelImage();
        rSMTextFullUsuario = new rojeru_san.RSMTextFull();
        rSMPassViewPassword = new rojeru_san.RSMPassView();
        rSButtonRiple1 = new rojeru_san.RSButtonRiple();
        rSButtonRiple2 = new rojeru_san.RSButtonRiple();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSButtonRiple3 = new rojeru_san.RSButtonRiple();
        JlabelUsuario = new javax.swing.JLabel();
        JlabelPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/lbl-user.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 190, 90));

        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/password.png"))); // NOI18N
        jPanel1.add(rSLabelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 590, 600));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/wave.png"))); // NOI18N
        jPanel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 600));

        rSMTextFullUsuario.setPlaceholder("Ingresar Usuario");
        rSMTextFullUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMTextFullUsuarioActionPerformed(evt);
            }
        });
        rSMTextFullUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rSMTextFullUsuarioKeyReleased(evt);
            }
        });
        jPanel1.add(rSMTextFullUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 290, -1));

        rSMPassViewPassword.setPlaceholder("Ingresar Contraseña");
        rSMPassViewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rSMPassViewPasswordKeyReleased(evt);
            }
        });
        jPanel1.add(rSMPassViewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 290, -1));

        rSButtonRiple1.setBorder(null);
        rSButtonRiple1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/btn-minimizar.png"))); // NOI18N
        rSButtonRiple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRiple1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 40, -1));

        rSButtonRiple2.setBorder(null);
        rSButtonRiple2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/btn-cerrar.png"))); // NOI18N
        rSButtonRiple2.setToolTipText("Cerrar");
        rSButtonRiple2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRiple2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 40, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/lbl-pass.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/lbl-user1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 40, 40));

        rSButtonRiple3.setBorder(null);
        rSButtonRiple3.setText("Iniciar Sesión");
        rSButtonRiple3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRiple3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, -1, -1));
        jPanel1.add(JlabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 190, 30));
        jPanel1.add(JlabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 130, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSMTextFullUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMTextFullUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMTextFullUsuarioActionPerformed

    private void rSButtonRiple2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rSButtonRiple2ActionPerformed

    private LoginVM login;
    private void rSButtonRiple3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple3ActionPerformed
//        Sistema sistema = new Sistema();
//        // sistema.setExtendedState(MAXIMIZED_BOTH);
//        sistema.setVisible(true);
//        dispose();
        ArrayList<JLabel> label = new ArrayList();
        label.add(JlabelUsuario);
        label.add(JlabelPassword);
        ArrayList<JTextField> texFile = new ArrayList();
        texFile.add(rSMTextFullUsuario);
        texFile.add(rSMPassViewPassword);
        login = new LoginVM(label, texFile);
        Object[] objects = login.Login();
    }//GEN-LAST:event_rSButtonRiple3ActionPerformed

    private void rSButtonRiple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple1ActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_rSButtonRiple1ActionPerformed

    private void rSMTextFullUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rSMTextFullUsuarioKeyReleased
        if (rSMTextFullUsuario.getText().equals("")) {
            JlabelUsuario.setForeground(new Color(102, 102, 102));
        } else {
            JlabelUsuario.setText("Usuario");
            JlabelUsuario.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_rSMTextFullUsuarioKeyReleased

    private void rSMPassViewPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rSMPassViewPasswordKeyReleased
        if (rSMPassViewPassword.getText().equals("")) {
            JlabelPassword.setForeground(new Color(102, 102, 102));
        } else {
            JlabelPassword.setText("Password");
            JlabelPassword.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_rSMPassViewPasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelPassword;
    private javax.swing.JLabel JlabelUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.RSButtonRiple rSButtonRiple1;
    private rojeru_san.RSButtonRiple rSButtonRiple2;
    private rojeru_san.RSButtonRiple rSButtonRiple3;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSLabelImage rSLabelImage2;
    private rojeru_san.RSMPassView rSMPassViewPassword;
    private rojeru_san.RSMTextFull rSMTextFullUsuario;
    private rojerusan.RSMetroTextFullPlaceHolderBeanInfo rSMetroTextFullPlaceHolderBeanInfo1;
    // End of variables declaration//GEN-END:variables
}
