/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Libreria.Objetos;
import ViewModels.ClientesVM;
import java.awt.Color;
import java.awt.image.BandCombineOp;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author elmer
 */
public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    public Sistema() {

        initComponents();

        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelLogo, "src/Recursos/xd.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelImgCliente, "src/Recursos/login.png");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        TabbedPanePrincipal = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextFieldBuscarCliente = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        TabbedPaneCliente1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabelImgCliente = new javax.swing.JLabel();
        jLabelCliente_Nid = new javax.swing.JLabel();
        TextFielCliente_Nid = new javax.swing.JTextField();
        TextFieldClienteNombre = new javax.swing.JTextField();
        jLabelCliente_email = new javax.swing.JLabel();
        TextFieldEmail = new javax.swing.JTextField();
        jLabelCliente_tel = new javax.swing.JLabel();
        TextFieldTelefono = new javax.swing.JTextField();
        jLabelCliente_apellido = new javax.swing.JLabel();
        TextFieldClienteApellido = new javax.swing.JTextField();
        jLabelCliente_direcc = new javax.swing.JLabel();
        TextFieldDireccion = new javax.swing.JTextField();
        CheckBoxCliente_Credito = new javax.swing.JCheckBox();
        jLabelCliente_Nombre = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        labelCliente_Pago = new javax.swing.JLabel();
        labelCliente_Ticket = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        labelCliente_Deuda = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelCliente_Deuda3 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        labelCliente_Deuda4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelCliente_Deuda5 = new javax.swing.JLabel();
        labelReport_pagos = new javax.swing.JLabel();
        TextFieldClientes_Pagos = new javax.swing.JTextField();
        jButtonClienteAgregar = new javax.swing.JButton();
        jButtonClienteCancelar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        TabbedPaneCliente2 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Clientes = Table_Clientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableCliente_Report = TableCliente_Report = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jLabelCliente_RegistroPaginas = new javax.swing.JLabel();
        innerPaginas_Clientes = new javax.swing.JSpinner();
        jPanel12 = new javax.swing.JPanel();
        ButtonCliente_Paginas1 = new javax.swing.JButton();
        ButtonCliente_Paginas2 = new javax.swing.JButton();
        ButtonCliente_Paginas3 = new javax.swing.JButton();
        ButtonCliente_Paginas4 = new javax.swing.JButton();
        LabelCliente_Paginas = new javax.swing.JLabel();
        jButtonCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema punto de venta");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelLogo.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
        );

        TabbedPanePrincipal.setBackground(new java.awt.Color(255, 255, 255));
        TabbedPanePrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabbedPanePrincipal.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1244, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        TabbedPanePrincipal.addTab("Ventas", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 106, 124));
        jLabel2.setText("Clientes");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 106, 124));
        jLabel3.setText("Buscar");

        TextFieldBuscarCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(TextFieldBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TabbedPaneCliente1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneCliente1StateChanged(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 106, 124));
        jLabel4.setText("Informacion del cliente");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 1, -1, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImgCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelImgCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelImgCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImgClienteMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelImgCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 144, 120));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 26, -1, -1));

        jLabelCliente_Nid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCliente_Nid.setForeground(new java.awt.Color(70, 106, 124));
        jLabelCliente_Nid.setText("Nid");
        jPanel6.add(jLabelCliente_Nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 154, 133, 25));

        TextFielCliente_Nid.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TextFielCliente_Nid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFielCliente_NidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFielCliente_NidKeyTyped(evt);
            }
        });
        jPanel6.add(TextFielCliente_Nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 185, 133, -1));

        TextFieldClienteNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TextFieldClienteNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldClienteNombreActionPerformed(evt);
            }
        });
        TextFieldClienteNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldClienteNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldClienteNombreKeyTyped(evt);
            }
        });
        jPanel6.add(TextFieldClienteNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 185, 130, -1));

        jLabelCliente_email.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCliente_email.setForeground(new java.awt.Color(70, 106, 124));
        jLabelCliente_email.setText("Email");
        jPanel6.add(jLabelCliente_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 133, 25));

        TextFieldEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldEmailKeyReleased(evt);
            }
        });
        jPanel6.add(TextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 255, 130, -1));

        jLabelCliente_tel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCliente_tel.setForeground(new java.awt.Color(70, 106, 124));
        jLabelCliente_tel.setText("Telefono");
        jPanel6.add(jLabelCliente_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 288, 133, 25));

        TextFieldTelefono.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TextFieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldTelefonoKeyTyped(evt);
            }
        });
        jPanel6.add(TextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 319, 133, -1));

        jLabelCliente_apellido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCliente_apellido.setForeground(new java.awt.Color(70, 106, 124));
        jLabelCliente_apellido.setText("Apellido");
        jPanel6.add(jLabelCliente_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 230, 133, 25));

        TextFieldClienteApellido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TextFieldClienteApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldClienteApellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldClienteApellidoKeyTyped(evt);
            }
        });
        jPanel6.add(TextFieldClienteApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 255, 133, -1));

        jLabelCliente_direcc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCliente_direcc.setForeground(new java.awt.Color(70, 106, 124));
        jLabelCliente_direcc.setText("Dirección");
        jPanel6.add(jLabelCliente_direcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 288, 133, 25));

        TextFieldDireccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TextFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDireccionActionPerformed(evt);
            }
        });
        TextFieldDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldDireccionKeyReleased(evt);
            }
        });
        jPanel6.add(TextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 319, 130, -1));

        CheckBoxCliente_Credito.setText("Credito");
        jPanel6.add(CheckBoxCliente_Credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 352, -1, -1));

        jLabelCliente_Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCliente_Nombre.setForeground(new java.awt.Color(70, 106, 124));
        jLabelCliente_Nombre.setText("Nombre");
        jPanel6.add(jLabelCliente_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 154, 133, 25));

        TabbedPaneCliente1.addTab("Registro de Cliente", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(70, 106, 124));
        jLabel5.setText("Reportes de pago");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel6.setForeground(new java.awt.Color(70, 106, 124));
        jLabel6.setText("Nombre del Cliente");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel7.setForeground(new java.awt.Color(70, 106, 124));
        jLabel7.setText("Número del ticket");

        labelCliente_Pago.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelCliente_Pago.setForeground(new java.awt.Color(70, 106, 124));
        labelCliente_Pago.setText("Ticket:");

        labelCliente_Ticket.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelCliente_Ticket.setForeground(new java.awt.Color(70, 106, 124));
        labelCliente_Ticket.setText("0000000000");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(labelCliente_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCliente_Ticket)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCliente_Ticket)
                    .addComponent(labelCliente_Pago))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 290, 70));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setForeground(new java.awt.Color(70, 106, 124));
        jLabel9.setText("Ultimo pago del Cliente");

        labelCliente_Deuda.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelCliente_Deuda.setForeground(new java.awt.Color(70, 106, 124));
        labelCliente_Deuda.setText("0.00");

        jLabel10.setForeground(new java.awt.Color(70, 106, 124));
        jLabel10.setText("Fecha de pago");

        labelCliente_Deuda3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelCliente_Deuda3.setForeground(new java.awt.Color(70, 106, 124));
        labelCliente_Deuda3.setText("--/--/--");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(labelCliente_Deuda, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCliente_Deuda3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap())))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCliente_Deuda3)
                    .addComponent(labelCliente_Deuda))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 290, 70));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel11.setForeground(new java.awt.Color(70, 106, 124));
        jLabel11.setText("Deuda del Cliente");

        labelCliente_Deuda4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelCliente_Deuda4.setForeground(new java.awt.Color(70, 106, 124));
        labelCliente_Deuda4.setText("0.00");

        jLabel12.setForeground(new java.awt.Color(70, 106, 124));
        jLabel12.setText("Fecha de la deuda");

        labelCliente_Deuda5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelCliente_Deuda5.setForeground(new java.awt.Color(70, 106, 124));
        labelCliente_Deuda5.setText("--/--/--");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(labelCliente_Deuda4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCliente_Deuda5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap())))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCliente_Deuda5)
                    .addComponent(labelCliente_Deuda4))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 290, 70));

        labelReport_pagos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelReport_pagos.setForeground(new java.awt.Color(70, 106, 124));
        labelReport_pagos.setText("Pagos");
        jPanel7.add(labelReport_pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 60, 30));

        TextFieldClientes_Pagos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel7.add(TextFieldClientes_Pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 220, 30));

        TabbedPaneCliente1.addTab("Pagos y reportes", jPanel7);

        jButtonClienteAgregar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonClienteAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClienteAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Agregar.png"))); // NOI18N
        jButtonClienteAgregar.setText("Agregar");
        jButtonClienteAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClienteAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteAgregarActionPerformed(evt);
            }
        });

        jButtonClienteCancelar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonClienteCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClienteCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cancelar.png"))); // NOI18N
        jButtonClienteCancelar.setText("Cancelar");
        jButtonClienteCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClienteCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPaneCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButtonClienteAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonClienteCancelar)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPaneCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClienteCancelar)
                    .addComponent(jButtonClienteAgregar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TabbedPaneCliente2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneCliente2StateChanged(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Table_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_ClientesMouseClicked(evt);
            }
        });
        Table_Clientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_ClientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Clientes);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPaneCliente2.addTab("Lista de Clientes", jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));

        TableCliente_Report.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TableCliente_Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCliente_ReportMouseClicked(evt);
            }
        });
        TableCliente_Report.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableCliente_ReportKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TableCliente_Report);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPaneCliente2.addTab("Pagos y reportes", jPanel11);

        jLabelCliente_RegistroPaginas.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabelCliente_RegistroPaginas.setForeground(new java.awt.Color(70, 106, 124));
        jLabelCliente_RegistroPaginas.setText("Registro por páginas :V");

        innerPaginas_Clientes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                innerPaginas_ClientesStateChanged(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ButtonCliente_Paginas1.setBackground(new java.awt.Color(102, 102, 102));
        ButtonCliente_Paginas1.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCliente_Paginas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Left-12.png"))); // NOI18N
        ButtonCliente_Paginas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCliente_Paginas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCliente_Paginas1ActionPerformed(evt);
            }
        });

        ButtonCliente_Paginas2.setBackground(new java.awt.Color(102, 102, 102));
        ButtonCliente_Paginas2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCliente_Paginas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Left.png"))); // NOI18N
        ButtonCliente_Paginas2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCliente_Paginas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCliente_Paginas2ActionPerformed(evt);
            }
        });

        ButtonCliente_Paginas3.setBackground(new java.awt.Color(102, 102, 102));
        ButtonCliente_Paginas3.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCliente_Paginas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Right.png"))); // NOI18N
        ButtonCliente_Paginas3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCliente_Paginas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCliente_Paginas3ActionPerformed(evt);
            }
        });

        ButtonCliente_Paginas4.setBackground(new java.awt.Color(102, 102, 102));
        ButtonCliente_Paginas4.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCliente_Paginas4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Right-12.png"))); // NOI18N
        ButtonCliente_Paginas4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCliente_Paginas4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCliente_Paginas4ActionPerformed(evt);
            }
        });

        LabelCliente_Paginas.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        LabelCliente_Paginas.setForeground(new java.awt.Color(70, 106, 124));
        LabelCliente_Paginas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCliente_Paginas.setText("Páginas");
        LabelCliente_Paginas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(ButtonCliente_Paginas1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(ButtonCliente_Paginas2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCliente_Paginas3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCliente_Paginas4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelCliente_Paginas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelCliente_Paginas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(ButtonCliente_Paginas1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonCliente_Paginas2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonCliente_Paginas3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonCliente_Paginas4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPaneCliente2)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCliente_RegistroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(innerPaginas_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TabbedPaneCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCliente_RegistroPaginas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(innerPaginas_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 489, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPanePrincipal.addTab("Clientes", jPanel3);

        jButtonCliente.setBackground(new java.awt.Color(102, 102, 102));
        jButtonCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/people.png"))); // NOI18N
        jButtonCliente.setText("Clientes");
        jButtonCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TabbedPanePrincipal)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButtonCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPanePrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="CODIGO DE CLIENTE">  
    private ClientesVM cliente;
    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
        ArrayList<JLabel> label = new ArrayList();
        label.add(jLabelCliente_Nid);
        label.add(jLabelCliente_RegistroPaginas);
        label.add(jLabelCliente_apellido);
        label.add(jLabelCliente_email);
        label.add(jLabelCliente_tel);
        label.add(jLabelCliente_direcc);
        label.add(jLabelImgCliente);
        label.add(LabelCliente_Paginas);

        ArrayList<JTextField> textField = new ArrayList();
        textField.add(TextFielCliente_Nid);
        textField.add(TextFieldClienteNombre);
        textField.add(TextFieldClienteApellido);
        textField.add(TextFieldEmail);
        textField.add(TextFieldTelefono);
        textField.add(TextFieldDireccion);

        Object[] objects = {CheckBoxCliente_Credito,
            Table_Clientes, innerPaginas_Clientes,
            TableCliente_Report};
        cliente = new ClientesVM(objects, label, textField);
        TabbedPanePrincipal.setSelectedIndex(1); // cuando presionamos este boton indicamos que pasamos a la tab 1 donde esta clientes

//        alertas.AlertWarningSalir alerta = new alertas.AlertWarningSalir(this,true);
//        alerta.titulo.setText("¿ESTAS SEGURO DE SALIR?");
//        alerta.setVisible(true);
    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jButtonClienteAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteAgregarActionPerformed

        cliente.RegistrarCliente();

        if (cliente.getInsert()) {
            alertas.AlertSuccess alerta = new alertas.AlertSuccess(this, true);
            alerta.Texto("Se ha registrado Correctamente");
            alerta.setVisible(true);
            rsscalelabel.RSScaleLabel.setScaleLabel(jLabelImgCliente, "src/Recursos/xd.png");
            cliente.setInsert(false);
        }
        if (cliente.getUpdate()) {
            alertas.AlertSuccess alerta = new alertas.AlertSuccess(this, true);
            alerta.Texto("Se ha Modificado Correctamente");
            alerta.setVisible(true);
            rsscalelabel.RSScaleLabel.setScaleLabel(jLabelImgCliente, "src/Recursos/xd.png");
            cliente.setUpdate(false);
        }
    }//GEN-LAST:event_jButtonClienteAgregarActionPerformed

    private void jButtonClienteCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteCancelarActionPerformed

        alertas.AlertWarning alerta = new alertas.AlertWarning(this, true);
        alerta.AgregarTexto("Seguro quieres cancelar", "Si", "No");
        alerta.setVisible(true);
        if (alerta.bandera) {

            cliente.restablecer();
            rsscalelabel.RSScaleLabel.setScaleLabel(jLabelImgCliente, "src/Recursos/login.png");
        }

    }//GEN-LAST:event_jButtonClienteCancelarActionPerformed

    private void jLabelImgClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImgClienteMouseClicked
        Objetos.uploadimagen.CargarImagen(jLabelImgCliente);

    }//GEN-LAST:event_jLabelImgClienteMouseClicked

    private void TextFielCliente_NidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFielCliente_NidKeyReleased
        if (TextFielCliente_Nid.getText().equals("")) {
            jLabelCliente_Nid.setForeground(new Color(102, 102, 102));
        } else {
            jLabelCliente_Nid.setText("Nid");
            jLabelCliente_Nid.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextFielCliente_NidKeyReleased

    private void TextFielCliente_NidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFielCliente_NidKeyTyped
        Objetos.eventos.NumberKeyPress(evt);
    }//GEN-LAST:event_TextFielCliente_NidKeyTyped

    private void TextFieldClienteNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldClienteNombreKeyReleased
        if (TextFieldClienteNombre.getText().equals("")) {
            jLabelCliente_RegistroPaginas.setForeground(new Color(102, 102, 102));
        } else {
            jLabelCliente_RegistroPaginas.setText("Nombre");
            jLabelCliente_RegistroPaginas.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextFieldClienteNombreKeyReleased

    private void TextFieldClienteNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldClienteNombreKeyTyped
        Objetos.eventos.textKeyPress(evt);
    }//GEN-LAST:event_TextFieldClienteNombreKeyTyped

    private void TextFieldClienteApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldClienteApellidoKeyReleased
        if (TextFieldClienteApellido.getText().equals("")) {
            jLabelCliente_apellido.setForeground(new Color(102, 102, 102));
        } else {
            jLabelCliente_apellido.setText("Apellido");
            jLabelCliente_apellido.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextFieldClienteApellidoKeyReleased

    private void TextFieldClienteApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldClienteApellidoKeyTyped
        Objetos.eventos.textKeyPress(evt);
    }//GEN-LAST:event_TextFieldClienteApellidoKeyTyped

    private void TextFieldEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldEmailKeyReleased
        if (TextFieldEmail.getText().equals("")) {
            jLabelCliente_email.setForeground(new Color(102, 102, 102));
        } else {
            jLabelCliente_email.setText("Email");
            jLabelCliente_email.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextFieldEmailKeyReleased

    private void TextFieldTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldTelefonoKeyReleased
        if (TextFieldTelefono.getText().equals("")) {
            jLabelCliente_tel.setForeground(new Color(102, 102, 102));
        } else {
            jLabelCliente_tel.setText("Telefono");
            jLabelCliente_tel.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextFieldTelefonoKeyReleased

    private void TextFieldTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldTelefonoKeyTyped
        Objetos.eventos.NumberKeyPress(evt);
    }//GEN-LAST:event_TextFieldTelefonoKeyTyped

    private void TextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDireccionActionPerformed

    }//GEN-LAST:event_TextFieldDireccionActionPerformed

    private void TextFieldDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldDireccionKeyReleased
        if (TextFieldDireccion.getText().equals("")) {
            jLabelCliente_direcc.setForeground(new Color(102, 102, 102));
        } else {
            jLabelCliente_direcc.setText("Dirección");
            jLabelCliente_direcc.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextFieldDireccionKeyReleased

    private void TextFieldClienteNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldClienteNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldClienteNombreActionPerformed

    private void ButtonCliente_Paginas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCliente_Paginas1ActionPerformed
        cliente.Paginador("Primero");
    }//GEN-LAST:event_ButtonCliente_Paginas1ActionPerformed

    private void ButtonCliente_Paginas4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCliente_Paginas4ActionPerformed
        cliente.Paginador("Ultimo");
    }//GEN-LAST:event_ButtonCliente_Paginas4ActionPerformed

    private void ButtonCliente_Paginas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCliente_Paginas3ActionPerformed
        cliente.Paginador("Siguiente");
    }//GEN-LAST:event_ButtonCliente_Paginas3ActionPerformed

    private void ButtonCliente_Paginas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCliente_Paginas2ActionPerformed
        cliente.Paginador("Anterior");
    }//GEN-LAST:event_ButtonCliente_Paginas2ActionPerformed

    private void innerPaginas_ClientesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_innerPaginas_ClientesStateChanged
        cliente.Registro_Paginas();
    }//GEN-LAST:event_innerPaginas_ClientesStateChanged

    private void Table_ClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_ClientesKeyReleased
        if (Table_Clientes.getSelectedRows().length > 0) {
            cliente.GetCliente();
        }
    }//GEN-LAST:event_Table_ClientesKeyReleased

    private void Table_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ClientesMouseClicked
        if (Table_Clientes.getSelectedRows().length > 0) {
            cliente.GetCliente();
        }
    }//GEN-LAST:event_Table_ClientesMouseClicked

    private void TabbedPaneCliente1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneCliente1StateChanged
        switch (TabbedPaneCliente1.getSelectedIndex()) {
            case 0:
                if (TabbedPaneCliente2.getSelectedIndex() > 0) {
                    TabbedPaneCliente2.setSelectedIndex(0);
                    cliente.seccion = 1;
                    cliente.Registro_Paginas();
                }
                break;
            case 1:
                cliente.seccion = 2;
                TabbedPaneCliente2.setSelectedIndex(1);
                cliente.Registro_Paginas();
                break;
        }
    }//GEN-LAST:event_TabbedPaneCliente1StateChanged

    private void TabbedPaneCliente2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneCliente2StateChanged
        switch (TabbedPaneCliente2.getSelectedIndex()) {
            case 0:
                if (TabbedPaneCliente1.getSelectedIndex() > 0) {
                    TabbedPaneCliente1.setSelectedIndex(0);
                    cliente.seccion = 1;
                    cliente.Registro_Paginas();
                }
                break;
            case 1:
                cliente.seccion = 2;
                TabbedPaneCliente1.setSelectedIndex(1);
                cliente.Registro_Paginas();
                break;
        }
    }//GEN-LAST:event_TabbedPaneCliente2StateChanged

    private void TableCliente_ReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCliente_ReportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TableCliente_ReportMouseClicked

    private void TableCliente_ReportKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableCliente_ReportKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TableCliente_ReportKeyReleased
// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCliente_Paginas1;
    private javax.swing.JButton ButtonCliente_Paginas2;
    private javax.swing.JButton ButtonCliente_Paginas3;
    private javax.swing.JButton ButtonCliente_Paginas4;
    private javax.swing.JCheckBox CheckBoxCliente_Credito;
    private javax.swing.JLabel LabelCliente_Paginas;
    private javax.swing.JTabbedPane TabbedPaneCliente1;
    private javax.swing.JTabbedPane TabbedPaneCliente2;
    private javax.swing.JTabbedPane TabbedPanePrincipal;
    private javax.swing.JTable TableCliente_Report;
    private javax.swing.JTable Table_Clientes;
    public javax.swing.JTextField TextFielCliente_Nid;
    private javax.swing.JTextField TextFieldBuscarCliente;
    private javax.swing.JTextField TextFieldClienteApellido;
    private javax.swing.JTextField TextFieldClienteNombre;
    private javax.swing.JTextField TextFieldClientes_Pagos;
    private javax.swing.JTextField TextFieldDireccion;
    private javax.swing.JTextField TextFieldEmail;
    private javax.swing.JTextField TextFieldTelefono;
    private javax.swing.JSpinner innerPaginas_Clientes;
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonClienteAgregar;
    private javax.swing.JButton jButtonClienteCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCliente_Nid;
    private javax.swing.JLabel jLabelCliente_Nombre;
    private javax.swing.JLabel jLabelCliente_RegistroPaginas;
    private javax.swing.JLabel jLabelCliente_apellido;
    private javax.swing.JLabel jLabelCliente_direcc;
    private javax.swing.JLabel jLabelCliente_email;
    private javax.swing.JLabel jLabelCliente_tel;
    private javax.swing.JLabel jLabelImgCliente;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelCliente_Deuda;
    private javax.swing.JLabel labelCliente_Deuda3;
    private javax.swing.JLabel labelCliente_Deuda4;
    private javax.swing.JLabel labelCliente_Deuda5;
    private javax.swing.JLabel labelCliente_Pago;
    private javax.swing.JLabel labelCliente_Ticket;
    private javax.swing.JLabel labelReport_pagos;
    // End of variables declaration//GEN-END:variables
}
